### ISSUE TITLE
jsonwebtoken security vulnerability

### ISSUE THREAD

**Issue by girwin90** [contentful/node-apps-toolkit#127]
Hi,

Just raising an issue I was given via snyk - https://security.snyk.io/vuln/SNYK-JS-JSONWEBTOKEN-3180022 I was wondering whether a fix will be put in to update the jsonwebtoken package?

Thanks.

**Comment by kdamball** [comment]
Hi,

We always use a defined algorithm (i.e: `RS256`) whenever we use the `verify` method.

Thanks
