### ISSUE TITLE
Module not found: Can't resolve 'http2'

### ISSUE THREAD

**Issue by AbhilashG97** [contentful/node-apps-toolkit#20]
Hello, 

I'm trying to use this library with a front-end app created with the `create-contentful-app` CLI tool. 

I'm trying to generate an access key by making use of the `getManagementToken()` function but I get the following error - 

```bash
Failed to compile.

./node_modules/http2-wrapper/source/index.js
Module not found: Can't resolve 'http2' in '/Users/......./my-app/node_modules/http2-wrapper/source'
```

A sample of the code that I'm using is shown below - 

```javascript
...
...

import fs from "fs";
import path from "path";
import { getManagementToken } from "@contentful/node-apps-toolkit";

... 
...

// Config Screen
  async componentDidMount() {
    // Generate Access Token
    const spaceId = this.props.sdk.ids.space;
    const environmentId = this.props.sdk.ids.environment;
    const appId = this.props.sdk.ids.app;
    const privateKey = fs.readFileSync(
      path.join(__dirname, "../../", "keys/key.pem"),
      { encoding: "utf8" }
    );
    const appAccessToken = await getManagementToken(privateKey, {
      appInstallationId: appId,
      spaceId,
      environmentId,
    });

    console.log("App Access Token : ", appAccessToken);

    // Get current parameters of the app.
    // If the app is not installed yet, `parameters` will be `null`.
    let parameters: AppInstallationParameters | null = await this.props.sdk.app.getParameters();
    parameters = parameters ?? this.state.parameters;

    this.setState({ parameters }, () => {
      // Once preparation has finished, call `setReady` to hide
      // the loading screen and present the app to a user.
      this.props.sdk.app.setReady();
    });
  }
```

Can I please get help regarding this issue? I hope I didn't miss anything. 
Thank you so much.

## Steps to reproduce this issue - 

1. Create a sample app with `create-contentful-app` CLI.
2. Install the `node-apps-toolkit` library.
3. Import and use the `getManagementToken()` function.

**Comment by andipaetzold** [comment]
Hey @AbhilashG97,

the `node-apps-toolkit` library was built to be used by a backend application on a node server. It does not work within a browser.

It is not possible to get access to a management token from a Contentful frontend app. All methods that are available within frontend apps are documented in the [App SDK reference doc](https://www.contentful.com/developers/docs/extensibility/app-framework/sdk/).

If you want to learn how to use the `node-apps-toolkit`, have a look at our tutorial [Building a backend app](https://www.contentful.com/developers/docs/extensibility/app-framework/app-identities-and-events/).

**Comment by AbhilashG97** [comment]
Hello @andipaetzold, 

I see, my bad. Thank you so much for your reply. I have used an alternate approach now. 

I have also gone through the tutorials again, they were really helpful. 

Thank you so much again! 🎉
