### ISSUE TITLE
CanonicalRequestValidator forces all header values to be strings

### ISSUE THREAD

**Issue by iDVB** [contentful/node-apps-toolkit#37]
CanonicalRequestValidator forces all header values to be strings. Right now, using `@vendia/serverless-express` the `request` that comes thru is has at least one that is a number. `headers.content-length`

https://github.com/contentful/node-apps-toolkit/blob/4825c559b39d7563593a8eedbde565804dbb8b2f/src/requests/typings.ts#L51

Not sure how to solve for this issue and now getting ...
`ValidationError: Expected string, but was number in headers.content-length` in compiled code.

```typescript
import serverlessExpress, { getCurrentInvoke } from '@vendia/serverless-express' // @4.5.2
import { verifyRequest, CanonicalRequest } from '@contentful/node-apps-toolkit' // @2.0.0

...

app.post('/webhook', async (req, res) => {
  const { event, context } = getCurrentInvoke()

  const canonicalRequest = {
    path: req.url,
    headers: req.headers,
    method: req.method,
    body: JSON.stringify(req.body),
  } as CanonicalRequest

  console.log(util.inspect({ event, req }, false, null))

  try {
    const isValid = verifyRequest(context.signingSecret, canonicalRequest)
    if (!isValid) {
      res.status(403).send('Unauthorized')
    }
  } catch (e) {
    console.error(e)
    res.status(403).send('Unauthorized')
  }
  res.status(200)
})


// event.headers['content-length'] === "420" string
// req.headers['content-length'] === 420 number
```

**Comment by Jwhiles** [comment]
Hey @iDVB could you provide a simple example to reproduce this?

**Comment by iDVB** [comment]
@Jwhiles yes, of course, now updated above.

**Comment by Jwhiles** [comment]
Hey @iDVB I've replicated something similar in plain express, and don't have the same issue. I think your issue is something that needs to solved in Vendia. To my knowledge all header values should be strings, and ideally we don't want to support invalid input in this library.

If this is not fixable in Vendia - I think you may just need to convert the headers back to strings before using `verifyRequest`

**Comment by iDVB** [comment]
@Jwhiles K thanks!
