### ISSUE TITLE
Cache key is not unique per space

### ISSUE THREAD

**Issue by jensbodal** [contentful/node-apps-toolkit#44]
Sorry if I missed this in the contributing guidelines, but I followed them as best I saw.

I created a PR here https://github.com/contentful/node-apps-toolkit/pull/43

I wasn’t sure if a related issue was necessary for tracking.

Currently the cache key is not unique between spaces which is problematic if creating a service that multiple spaces I own will consume.

**Comment by shikaan** [comment]
Hey @jensbodal
Thanks a lot for your contribution :) The pull request is approved and it's being shipped as we speak. Feel free to reopen the issue, should you encounter any other problem.

Have a great day,
Manuel
